apiVersion: v1
kind: Service
metadata:
  name: devraq-agent-backend-service
  namespace: thinkcloud
spec:
  selector:
    app: devraq-agent-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: ClusterIP
